"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import type { LangCode } from "@/lib/domain";

export const LANGUAGES: { code: LangCode; nativeName: string; rtl: boolean }[] = [
  { code: "fr", nativeName: "Français", rtl: false },
  { code: "ar", nativeName: "العربية", rtl: true },
  { code: "en", nativeName: "English", rtl: false },
];

const STORAGE_KEY = "central-language";

/** Core UI strings. Content (product names…) falls back fr → base row. */
const STRINGS: Record<LangCode, Record<string, string>> = {
  fr: {
    dashboard: "Tableau de bord",
    orders: "Commandes",
    online_orders: "En ligne",
    products: "Produits",
    categories: "Catégories",
    reports: "Rapports",
    settings: "Paramètres",
    business_settings: "Établissement",
    overview: "Vue d'ensemble",
    search: "Rechercher…",
    search_products: "Rechercher un produit…",
    search_orders: "N°, serveur, client…",
    all: "Tous",
    all_categories: "Toutes catégories",
    all_statuses: "Tous statuts",
    add: "Ajouter",
    add_product: "Ajouter un produit",
    edit_product: "Modifier le produit",
    new_product: "Nouveau produit",
    save: "Enregistrer",
    saving: "Enregistrement…",
    cancel: "Annuler",
    delete: "Supprimer",
    confirm: "Confirmer",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    actions: "Actions",
    name: "Nom",
    price: "Prix",
    category: "Catégorie",
    status: "Statut",
    type: "Type",
    available: "Disponible",
    unavailable: "Indisponible",
    details: "Détails",
    variants: "Variantes",
    variants_hint: "Prix final = prix du produit + ajustement.",
    variants_options: "Options",
    variants_options_hint: "Partagées par tous les produits. Cochez-en une ou deux puis générez la matrice.",
    variants_add_option: "Nouvelle option (ex. Poids)",
    variants_add_value: "Ajouter une valeur",
    variants_generate: "Générer les variantes",
    variants_created: "variante(s) créée(s)",
    variants_none_created: "Aucune nouvelle variante à créer.",
    variants_delete_blocked: "Certaines variantes sont utilisées par des commandes et n'ont pas pu être supprimées.",
    variants_base_price: "prix de base",
    variants_price_mod: "Ajustement",
    variant_image: "Image de la variante",
    variant_weight: "Poids",
    variant_weight_unit: "Unité",
    variant_track_stock: "Suivre le stock",
    variants_kind_select: "liste",
    variants_kind_color: "couleur",
    media: "Images",
    pricing: "Tarification",
    revenue: "Chiffre d'affaires",
    orders_today: "Commandes du jour",
    avg_ticket: "Ticket moyen",
    completion: "Complétion",
    active_orders: "En cours",
    recent_orders: "Commandes récentes",
    top_products: "Meilleures ventes",
    hourly_revenue: "Revenu par heure",
    view_all: "Tout voir",
    no_results: "Aucun résultat",
    no_results_hint: "Essayez d'ajuster la recherche ou les filtres.",
    clear_filters: "Effacer les filtres",
    empty_products: "Aucun produit",
    empty_products_hint: "Créez votre premier produit pour remplir le catalogue.",
    empty_orders: "Aucune commande",
    empty_orders_hint: "Les commandes du point de vente apparaîtront ici.",
    empty_online_orders: "Aucune commande en ligne",
    empty_online_orders_hint: "Les commandes de la boutique apparaîtront ici.",
    empty_categories: "Aucune catégorie",
    empty_categories_hint: "Organisez le catalogue avec des catégories.",
    loading: "Chargement…",
    error_title: "Quelque chose a mal tourné",
    retry: "Réessayer",
    no_access_title: "Aucun établissement accessible",
    no_access_body: "Votre compte n'est rattaché à aucun établissement. Contactez votre administrateur.",
    total: "Total",
    subtotal: "Sous-total",
    delivery: "Livraison",
    description: "Description",
    short_description: "Description courte",
    long_description: "Description détaillée",
    long_description_hint: "Affichée sur la fiche produit de la boutique en ligne. Mise en forme Markdown prise en charge.",
    preview: "Aperçu",
    edit: "Éditer",
    md_bold: "Gras",
    md_italic: "Italique",
    md_heading: "Titre",
    md_bullet_list: "Liste à puces",
    md_numbered_list: "Liste numérotée",
    md_quote: "Citation",
    md_link: "Lien",
    md_image: "Image",
    media_picker_title: "Choisir une photo",
    media_picker_hint: "Sélectionnez une image.",
    media_picker_empty: "Aucune image disponible.",
    media_upload: "Téléverser",
    media_url: "URL de l'image",
    media_library: "Médiathèque",
    media_library_hint: "Toutes les images de l'établissement : organisez-les par dossier, étiquette ou favori, puis réutilisez-les dans les produits et les descriptions.",
    media_selected: "sélectionnée(s)",
    media_attach: "Ajouter au produit",
    media_already_attached: "Déjà présente sur ce produit.",
    media_folders: "Dossiers",
    media_all_folders: "Tous les dossiers",
    media_tags: "Étiquettes",
    media_all_tags: "Toutes les étiquettes",
    media_favorites: "Favoris",
    media_asset_alt: "Texte alternatif",
    media_asset_folder: "Dossier",
    media_file_kept: "Fichier conservé : il est encore utilisé par un produit.",
    media_deleted: "Image supprimée.",
    media_root: "Racine",
    category_image: "Image de la catégorie",
    name_hint: "Affiché sur la boutique en ligne pour cette langue.",
    name_translations: "Nom par langue",
    name_primary_hint: "Nom principal du produit, utilisé quand aucune traduction n'est définie.",
    media_hint: "Affichées sur la fiche produit de la boutique en ligne. La photo principale s'affiche en premier.",
    media_save_first: "Enregistrez le produit pour ajouter des photos.",
    photo_add: "Ajouter des photos",
    photo_drop: "Glissez des photos ici",
    photo_primary: "Principale",
    photo_set_primary: "Définir comme principale",
    photo_empty: "Aucune photo",
    photo_remove: "Supprimer la photo",
    photo_remove_confirm: "La photo sera supprimée définitivement de la boutique en ligne.",
    photo_move_earlier: "Déplacer avant",
    photo_move_later: "Déplacer après",
    photo_upload_failed: "Échec du téléversement",
    photo_too_large: "Image trop lourde (5 Mo maximum)",
    photo_unsupported: "Format non pris en charge (JPEG, PNG, WebP, GIF)",
    customer: "Client",
    phone: "Téléphone",    address: "Adresse",
    wilaya: "Wilaya",
    commune: "Commune",
    payment: "Paiement",
    shipping: "Expédition",
    date: "Date",
    quantity: "Qté",
    export_csv: "Exporter CSV",
    language: "Langue",
    theme: "Thème",
    light: "Clair",
    dark: "Sombre",
    system: "Système",
    logout: "Déconnexion",
    login_subtitle: "Le centre de contrôle de votre établissement.",
    email: "E-mail",
    password: "Mot de passe",
    sign_in: "Se connecter",
    continue_demo: "Continuer en démo",
    continue_with_google: "Continuer avec Google",
    redirecting_to_google: "Redirection vers Google…",
    or_email: "ou par e-mail",
    err_oauth_failed: "La connexion Google a échoué. Réessayez ou utilisez l'e-mail.",
    err_invalid_credentials: "E-mail ou mot de passe invalide.",
    err_access_denied: "Ce compte n'a pas accès à la console.",
    err_oauth_unconfigured: "La connexion Google n'est pas encore configurée. Utilisez l'e-mail et le mot de passe.",
    register: "Créer un compte",
    full_name: "Nom complet",
    confirm_password: "Confirmer le mot de passe",
    no_account: "Pas encore de compte ?",
    has_account: "Déjà un compte ?",
    forgot_password: "Mot de passe oublié ?",
    reset_password: "Réinitialiser",
    reset_sent: "Lien envoyé — vérifiez votre boîte e-mail.",
    back_to_login: "Retour à la connexion",
    passwords_mismatch: "Les mots de passe ne correspondent pas.",
    trial: "Essai",
    suspended: "Suspendu",
    cancelled: "Résilié",
    trial_days_left: "jours d'essai restants",
    general: "Général",
    ordering: "Commandes",
    storefront: "Boutique",
    branding: "Marque",
    location: "Emplacement",
    unsaved_changes: "Modifications non enregistrées",
    discard: "Abandonner",
    saved: "Enregistré",
    product_saved: "Produit enregistré.",
    product_created: "Produit créé.",
    product_deleted: "Produit supprimé.",
    confirm_delete_title: "Supprimer cet élément ?",
    confirm_delete_body: "Cette action est irréversible.",
    bulk_select: "Sélectionner",
    bulk_selected_count: "{n} sélectionné(s)",
    bulk_actions: "Actions",
    bulk_clear: "Tout désélectionner",
    bulk_set_available: "Rendre disponibles",
    bulk_set_unavailable: "Rendre indisponibles",
    bulk_move_to_category: "Déplacer vers une catégorie",
    bulk_move_body: "Les produits sélectionnés seront déplacés vers la catégorie choisie.",
    bulk_move_done: "Produits déplacés.",
    bulk_available_done: "Produits maintenant disponibles.",
    bulk_unavailable_done: "Produits maintenant indisponibles.",
    bulk_delete_title: "Supprimer {n} produit(s) ?",
    bulk_delete_body: "Cette action est irréversible. Les produits utilisés dans des commandes ne peuvent pas être supprimés.",
    bulk_delete_done: "{n} produit(s) supprimé(s).",
    bulk_delete_blocked: "{n} produit(s) non supprimable(s) (utilisés dans des commandes).",
    hero_editor: "Accueil — Hero",
    hero_editor_hint: "Bandeau principal de la boutique en ligne",
    hero_editor_note: "Laissez vide pour utiliser le contenu par défaut de la boutique. Enregistrer remplace les textes et images du bandeau d'accueil pour les trois langues.",
    hero_headline: "Titre et accroche",
    hero_two_lines: "première ligne",
    hero_title_lead: "Titre — ligne 1",
    hero_title_tail: "Titre — ligne 2",
    hero_support: "Phrase de soutien",
    hero_ctas: "Boutons d'action",
    hero_primary_cta: "Bouton principal",
    hero_primary_href: "Lien du bouton principal",
    hero_secondary_cta: "Lien secondaire",
    hero_secondary_href: "Lien secondaire (URL)",
    hero_images: "Images",
    hero_image_desktop: "Image bureau (paysage)",
    hero_image_mobile: "Image mobile (portrait)",
    hero_image_alt: "Texte alternatif",
    hero_saved: "Bandeau enregistré.",
    hero_preview: "Aperçu",
    hero_preview_hint: "Aperçu indicatif — la page publiée reste la référence finale.",
    hero_preview_no_image: "Aucune image — bandeau par défaut",
    cost_price: "Prix de revient",
    margin: "Marge",
    sku: "SKU",
    barcode: "Code-barres",
    printer: "Imprimante",
    kitchen: "Cuisine",
    bar: "Bar",
    oven: "Four",
    none: "Aucune",
    simple: "Simple",
    variable: "Variable",
    composite: "Composé",
    parent_category: "Catégorie parente",
    top_level: "Racine",
    products_count: "produits",
    business: "Établissement",
    owner: "Propriétaire",
    stores: "Établissements",
    add_store: "Nouvel établissement",
    command_palette_hint: "Rechercher, naviguer, agir…",
    go_to: "Aller à",
    today: "Aujourd'hui",
    last_7_days: "7 derniers jours",
    last_30_days: "30 derniers jours",
    daily_revenue: "Revenu quotidien",
    payment_methods: "Moyens de paiement",
    breakdown: "Détail journalier",
    mark: "Marquer",
    tracking_number: "N° de suivi",
    mark_shipped: "Marquer expédiée",
    mark_delivered: "Marquer livrée",
    onboarding_title: "Configurez votre établissement",
    onboarding_subtitle: "Quelques informations pour commencer.",
    store_name: "Nom de l'établissement",
    finish: "Terminer",
    skip: "Passer",
    welcome: "Bienvenue",
  },
  ar: {
    dashboard: "لوحة القيادة",
    orders: "الطلبات",
    online_orders: "عبر الإنترنت",
    products: "المنتجات",
    categories: "الفئات",
    reports: "التقارير",
    settings: "الإعدادات",
    business_settings: "المؤسسة",
    overview: "نظرة عامة",
    search: "بحث…",
    search_products: "ابحث عن منتج…",
    search_orders: "الرقم، النادل، الزبون…",
    all: "الكل",
    all_categories: "كل الفئات",
    all_statuses: "كل الحالات",
    add: "إضافة",
    add_product: "إضافة منتج",
    edit_product: "تعديل المنتج",
    new_product: "منتج جديد",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    cancel: "إلغاء",
    delete: "حذف",
    confirm: "تأكيد",
    close: "إغلاق",
    back: "رجوع",
    next: "التالي",
    actions: "إجراءات",
    name: "الاسم",
    price: "السعر",
    category: "الفئة",
    status: "الحالة",
    type: "النوع",
    available: "متوفر",
    unavailable: "غير متوفر",
    details: "التفاصيل",
    variants: "الأنواع",
    variants_hint: "السعر النهائي = سعر المنتج + التعديل.",
    variants_options: "الخيارات",
    variants_options_hint: "مشتركة بين كل المنتجات. اختر واحداً أو اثنين ثم أنشئ المصفوفة.",
    variants_add_option: "خيار جديد (مثال: الوزن)",
    variants_add_value: "إضافة قيمة",
    variants_generate: "إنشاء الخيارات",
    variants_created: "خيار تم إنشاؤه",
    variants_none_created: "لا توجد خيارات جديدة.",
    variants_delete_blocked: "بعض الخيارات مستخدمة في طلبات ولم يُمكن حذفها.",
    variants_base_price: "السعر الأساسي",
    variants_price_mod: "تعديل السعر",
    variant_image: "صورة الخيار",
    variant_weight: "الوزن",
    variant_weight_unit: "الوحدة",
    variant_track_stock: "تتبع المخزون",
    variants_kind_select: "قائمة",
    variants_kind_color: "لون",
    media: "الصور",
    pricing: "التسعير",
    revenue: "رقم الأعمال",
    orders_today: "طلبات اليوم",
    avg_ticket: "متوسط السلة",
    completion: "الإتمام",
    active_orders: "قيد التحضير",
    recent_orders: "الطلبات الأخيرة",
    top_products: "الأكثر مبيعًا",
    hourly_revenue: "الإيراد بالساعة",
    view_all: "عرض الكل",
    no_results: "لا نتائج",
    no_results_hint: "جرّب تعديل البحث أو المرشحات.",
    clear_filters: "مسح المرشحات",
    empty_products: "لا منتجات",
    empty_products_hint: "أنشئ أول منتج لملء الكتالوج.",
    empty_orders: "لا طلبات",
    empty_orders_hint: "ستظهر طلبات نقطة البيع هنا.",
    empty_online_orders: "لا طلبات عبر الإنترنت",
    empty_online_orders_hint: "ستظهر طلبات المتجر هنا.",
    empty_categories: "لا فئات",
    empty_categories_hint: "نظّم الكتالوج بالفئات.",
    loading: "جارٍ التحميل…",
    error_title: "حدث خطأ ما",
    retry: "إعادة المحاولة",
    no_access_title: "لا توجد مؤسسة مرتبطة",
    no_access_body: "حسابك غير مرتبط بأي مؤسسة. اتصل بالمسؤول.",
    total: "المجموع",
    subtotal: "المجموع الفرعي",
    delivery: "التوصيل",
    description: "الوصف",
    short_description: "وصف قصير",
    long_description: "وصف تفصيلي",
    long_description_hint: "يظهر في صفحة المنتج بالمتجر الإلكتروني. يدعم تنسيق Markdown.",
    preview: "معاينة",
    edit: "تحرير",
    md_bold: "عريض",
    md_italic: "مائل",
    md_heading: "عنوان",
    md_bullet_list: "قائمة نقطية",
    md_numbered_list: "قائمة مرقّمة",
    md_quote: "اقتباس",
    md_link: "رابط",
    md_image: "صورة",
    media_picker_title: "اختيار صورة",
    media_picker_hint: "اختر صورة.",
    media_picker_empty: "لا توجد صور متاحة.",
    media_upload: "رفع صورة",
    media_url: "رابط الصورة",
    media_library: "مكتبة الوسائط",
    media_library_hint: "جميع صور المؤسسة: نظّمها بالمجلدات والوسوم والمفضلة، ثم أعد استخدامها في المنتجات والأوصاف.",
    media_selected: "محددة",
    media_attach: "إضافة إلى المنتج",
    media_already_attached: "موجودة مسبقاً في هذا المنتج.",
    media_folders: "المجلدات",
    media_all_folders: "كل المجلدات",
    media_tags: "الوسوم",
    media_all_tags: "كل الوسوم",
    media_favorites: "المفضلة",
    media_asset_alt: "النص البديل",
    media_asset_folder: "المجلد",
    media_file_kept: "تم الاحتفاظ بالملف: ما زال مستخدماً في منتج.",
    media_deleted: "تم حذف الصورة.",
    media_root: "الجذر",
    category_image: "صورة الفئة",
    name_hint: "يظهر في المتجر الإلكتروني بهذه اللغة.",
    name_translations: "الاسم حسب اللغة",
    name_primary_hint: "الاسم الرئيسي للمنتج، يُستخدم عند غياب ترجمة.",
    media_hint: "تظهر في صفحة المنتج بالمتجر الإلكتروني. الصورة الرئيسية تظهر أولاً.",
    media_save_first: "احفظ المنتج لإضافة الصور.",
    photo_add: "إضافة صور",
    photo_drop: "أفلت الصور هنا",
    photo_primary: "رئيسية",
    photo_set_primary: "تعيين كرئيسية",
    photo_empty: "لا توجد صور",
    photo_remove: "حذف الصورة",
    photo_remove_confirm: "سيتم حذف الصورة نهائياً من المتجر الإلكتروني.",
    photo_move_earlier: "تحريك للأمام",
    photo_move_later: "تحريك للخلف",
    photo_upload_failed: "فشل رفع الصورة",
    photo_too_large: "حجم الصورة كبير جداً (5 ميغابايت كحد أقصى)",
    photo_unsupported: "صيغة غير مدعومة (JPEG، PNG، WebP، GIF)",
    customer: "الزبون",
    phone: "الهاتف",
    address: "العنوان",
    wilaya: "الولاية",
    commune: "البلدية",
    payment: "الدفع",
    shipping: "الشحن",
    date: "التاريخ",
    quantity: "الكمية",
    export_csv: "تصدير CSV",
    language: "اللغة",
    theme: "المظهر",
    light: "فاتح",
    dark: "داكن",
    system: "النظام",
    logout: "تسجيل الخروج",
    login_subtitle: "مركز التحكم في مؤسستك.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    sign_in: "تسجيل الدخول",
    continue_demo: "المتابعة كضيف",
    continue_with_google: "المتابعة عبر Google",
    redirecting_to_google: "جارٍ التحويل إلى Google…",
    or_email: "أو بالبريد الإلكتروني",
    err_oauth_failed: "فشل تسجيل الدخول عبر Google. حاول مجددًا أو استخدم البريد.",
    err_invalid_credentials: "البريد أو كلمة المرور غير صحيحة.",
    err_access_denied: "هذا الحساب لا يملك حق الوصول.",
    err_oauth_unconfigured: "تسجيل الدخول عبر Google غير مفعّل بعد. استخدم البريد وكلمة المرور.",
    register: "إنشاء حساب",
    full_name: "الاسم الكامل",
    confirm_password: "تأكيد كلمة المرور",
    no_account: "ليس لديك حساب؟",
    has_account: "لديك حساب؟",
    forgot_password: "نسيت كلمة المرور؟",
    reset_password: "إعادة تعيين",
    reset_sent: "تم إرسال الرابط — تحقق من بريدك.",
    back_to_login: "العودة لتسجيل الدخول",
    passwords_mismatch: "كلمتا المرور غير متطابقتين.",
    trial: "تجريبي",
    suspended: "موقوف",
    cancelled: "ملغى",
    trial_days_left: "أيام تجريبية متبقية",
    general: "عام",
    ordering: "الطلبات",
    storefront: "المتجر",
    branding: "العلامة",
    location: "الموقع",
    unsaved_changes: "تغييرات غير محفوظة",
    discard: "تجاهل",
    saved: "تم الحفظ",
    product_saved: "تم حفظ المنتج.",
    product_created: "تم إنشاء المنتج.",
    product_deleted: "تم حذف المنتج.",
    confirm_delete_title: "حذف هذا العنصر؟",
    confirm_delete_body: "هذا الإجراء لا يمكن التراجع عنه.",
    bulk_select: "تحديد",
    bulk_selected_count: "{n} محدد",
    bulk_actions: "إجراءات",
    bulk_clear: "إلغاء تحديد الكل",
    bulk_set_available: "جعلها متوفرة",
    bulk_set_unavailable: "جعلها غير متوفرة",
    bulk_move_to_category: "نقل إلى فئة",
    bulk_move_body: "ستنقل المنتجات المحددة إلى الفئة المختارة.",
    bulk_move_done: "تم نقل المنتجات.",
    bulk_available_done: "المنتجات متوفرة الآن.",
    bulk_unavailable_done: "المنتجات غير متوفرة الآن.",
    bulk_delete_title: "حذف {n} منتج؟",
    bulk_delete_body: "هذا الإجراء لا يمكن التراجع عنه. لا يمكن حذف المنتجات المستخدمة في طلبات.",
    bulk_delete_done: "تم حذف {n} منتج.",
    bulk_delete_blocked: "{n} منتج لم يمكن حذفها (مستخدمة في طلبات).",
    hero_editor: "الرئيسية — البانر",
    hero_editor_hint: "الشريط الرئيسي للمتجر الإلكتروني",
    hero_editor_note: "اتركه فارغاً لاستخدام المحتوى الافتراضي للمتجر. الحفظ يستبدل نصوص وصور البانر الرئيسي للغات الثلاث.",
    hero_headline: "العنوان والمقدمة",
    hero_two_lines: "السطر الأول",
    hero_title_lead: "العنوان — السطر 1",
    hero_title_tail: "العنوان — السطر 2",
    hero_support: "الجملة الداعمة",
    hero_ctas: "أزرار الإجراء",
    hero_primary_cta: "الزر الرئيسي",
    hero_primary_href: "رابط الزر الرئيسي",
    hero_secondary_cta: "الرابط الثانوي",
    hero_secondary_href: "رابط ثانوي (URL)",
    hero_images: "الصور",
    hero_image_desktop: "صورة سطح المكتب (عرضية)",
    hero_image_mobile: "صورة الجوال (طولية)",
    hero_image_alt: "النص البديل",
    hero_saved: "تم حفظ البانر.",
    hero_preview: "معاينة",
    hero_preview_hint: "معاينة تقريبية — الصفحة المنشورة هي المرجع النهائي.",
    hero_preview_no_image: "لا توجد صورة — بانر افتراضي",
    cost_price: "سعر التكلفة",
    margin: "الهامش",
    sku: "SKU",
    barcode: "الباركود",
    printer: "الطابعة",
    kitchen: "المطبخ",
    bar: "البار",
    oven: "الفرن",
    none: "لا شيء",
    simple: "بسيط",
    variable: "متغير",
    composite: "مركّب",
    parent_category: "الفئة الأم",
    top_level: "جذر",
    products_count: "منتجات",
    business: "المؤسسة",
    owner: "المالك",
    stores: "المؤسسات",
    add_store: "مؤسسة جديدة",
    command_palette_hint: "ابحث، تنقّل، نفّذ…",
    go_to: "انتقل إلى",
    today: "اليوم",
    last_7_days: "آخر ٧ أيام",
    last_30_days: "آخر ٣٠ يومًا",
    daily_revenue: "الإيراد اليومي",
    payment_methods: "طرق الدفع",
    breakdown: "التفصيل اليومي",
    mark: "تعليم",
    tracking_number: "رقم التتبع",
    mark_shipped: "تعليم كمشحونة",
    mark_delivered: "تعليم كمستلمة",
    onboarding_title: "أعدّ مؤسستك",
    onboarding_subtitle: "بعض المعلومات للبدء.",
    store_name: "اسم المؤسسة",
    finish: "إنهاء",
    skip: "تخطي",
    welcome: "مرحبًا",
  },
  en: {
    dashboard: "Dashboard",
    orders: "Orders",
    online_orders: "Online",
    products: "Products",
    categories: "Categories",
    reports: "Reports",
    settings: "Settings",
    business_settings: "Business",
    overview: "Overview",
    search: "Search…",
    search_products: "Search products…",
    search_orders: "No., waiter, customer…",
    all: "All",
    all_categories: "All categories",
    all_statuses: "All statuses",
    add: "Add",
    add_product: "Add product",
    edit_product: "Edit product",
    new_product: "New product",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    close: "Close",
    back: "Back",
    next: "Next",
    actions: "Actions",
    name: "Name",
    price: "Price",
    category: "Category",
    status: "Status",
    type: "Type",
    available: "Available",
    unavailable: "Unavailable",
    details: "Details",
    variants: "Variants",
    variants_hint: "Final price = product price + adjustment.",
    variants_options: "Options",
    variants_options_hint: "Shared by every product. Tick one or two, then generate the matrix.",
    variants_add_option: "New option (e.g. Weight)",
    variants_add_value: "Add a value",
    variants_generate: "Generate variants",
    variants_created: "variant(s) created",
    variants_none_created: "No new variant to create.",
    variants_delete_blocked: "Some variants are used by orders and could not be deleted.",
    variants_base_price: "base price",
    variants_price_mod: "Adjustment",
    variant_image: "Variant image",
    variant_weight: "Weight",
    variant_weight_unit: "Unit",
    variant_track_stock: "Track stock",
    variants_kind_select: "list",
    variants_kind_color: "colour",
    media: "Images",
    pricing: "Pricing",
    revenue: "Revenue",
    orders_today: "Today's orders",
    avg_ticket: "Avg. ticket",
    completion: "Completion",
    active_orders: "In progress",
    recent_orders: "Recent orders",
    top_products: "Top products",
    hourly_revenue: "Revenue by hour",
    view_all: "View all",
    no_results: "No results",
    no_results_hint: "Try adjusting search or filters.",
    clear_filters: "Clear filters",
    empty_products: "No products",
    empty_products_hint: "Create your first product to fill the catalog.",
    empty_orders: "No orders",
    empty_orders_hint: "Point-of-sale orders will appear here.",
    empty_online_orders: "No online orders",
    empty_online_orders_hint: "Storefront orders will appear here.",
    empty_categories: "No categories",
    empty_categories_hint: "Organize the catalog with categories.",
    loading: "Loading…",
    error_title: "Something went wrong",
    retry: "Retry",
    no_access_title: "No accessible business",
    no_access_body: "Your account is not linked to any business. Contact your administrator.",
    total: "Total",
    subtotal: "Subtotal",
    delivery: "Delivery",
    description: "Description",
    short_description: "Short description",
    long_description: "Long description",
    long_description_hint: "Shown on the online store product page. Markdown formatting supported.",
    preview: "Preview",
    edit: "Edit",
    md_bold: "Bold",
    md_italic: "Italic",
    md_heading: "Heading",
    md_bullet_list: "Bulleted list",
    md_numbered_list: "Numbered list",
    md_quote: "Quote",
    md_link: "Link",
    md_image: "Image",
    media_picker_title: "Choose a photo",
    media_picker_hint: "Select an image.",
    media_picker_empty: "No images available.",
    media_upload: "Upload",
    media_url: "Image URL",
    media_library: "Media library",
    media_library_hint: "Every image for this business: organise by folder, tag or favourite, then reuse them in products and descriptions.",
    media_selected: "selected",
    media_attach: "Add to product",
    media_already_attached: "Already on this product.",
    media_folders: "Folders",
    media_all_folders: "All folders",
    media_tags: "Tags",
    media_all_tags: "All tags",
    media_favorites: "Favorites",
    media_asset_alt: "Alt text",
    media_asset_folder: "Folder",
    media_file_kept: "File kept: a product still uses it.",
    media_deleted: "Image removed.",
    media_root: "Root",
    category_image: "Category image",
    name_hint: "Shown on the online store in this language.",
    name_translations: "Name per language",
    name_primary_hint: "Primary product name, used when no translation is set.",
    media_hint: "Shown on the online store product page. The primary photo is displayed first.",
    media_save_first: "Save the product to add photos.",
    photo_add: "Add photos",
    photo_drop: "Drop photos here",
    photo_primary: "Primary",
    photo_set_primary: "Set as primary",
    photo_empty: "No photos",
    photo_remove: "Remove photo",
    photo_remove_confirm: "The photo will be permanently removed from the online store.",
    photo_move_earlier: "Move earlier",
    photo_move_later: "Move later",
    photo_upload_failed: "Upload failed",
    photo_too_large: "Image too large (5 MB maximum)",
    photo_unsupported: "Unsupported format (JPEG, PNG, WebP, GIF)",
    customer: "Customer",
    phone: "Phone",
    address: "Address",
    wilaya: "Wilaya",
    commune: "Commune",
    payment: "Payment",
    shipping: "Shipping",
    date: "Date",
    quantity: "Qty",
    export_csv: "Export CSV",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    logout: "Sign out",
    login_subtitle: "Your business control plane.",
    email: "Email",
    password: "Password",
    sign_in: "Sign in",
    continue_demo: "Continue as demo",
    continue_with_google: "Continue with Google",
    redirecting_to_google: "Redirecting to Google…",
    or_email: "or email",
    err_oauth_failed: "Google sign-in failed. Try again or use email.",
    err_invalid_credentials: "Invalid email or password.",
    err_access_denied: "This account does not have console access.",
    err_oauth_unconfigured: "Google sign-in is not available yet (provider not configured). Use email and password.",
    register: "Create account",
    full_name: "Full name",
    confirm_password: "Confirm password",
    no_account: "No account yet?",
    has_account: "Already have an account?",
    forgot_password: "Forgot password?",
    reset_password: "Reset",
    reset_sent: "Link sent — check your inbox.",
    back_to_login: "Back to sign in",
    passwords_mismatch: "Passwords do not match.",
    trial: "Trial",
    suspended: "Suspended",
    cancelled: "Cancelled",
    trial_days_left: "trial days left",
    general: "General",
    ordering: "Ordering",
    storefront: "Storefront",
    branding: "Brand",
    location: "Location",
    unsaved_changes: "Unsaved changes",
    discard: "Discard",
    saved: "Saved",
    product_saved: "Product saved.",
    product_created: "Product created.",
    product_deleted: "Product deleted.",
    confirm_delete_title: "Delete this item?",
    confirm_delete_body: "This action cannot be undone.",
    bulk_select: "Select",
    bulk_selected_count: "{n} selected",
    bulk_actions: "Actions",
    bulk_clear: "Clear selection",
    bulk_set_available: "Make available",
    bulk_set_unavailable: "Make unavailable",
    bulk_move_to_category: "Move to category",
    bulk_move_body: "The selected products will be moved to the chosen category.",
    bulk_move_done: "Products moved.",
    bulk_available_done: "Products are now available.",
    bulk_unavailable_done: "Products are now unavailable.",
    bulk_delete_title: "Delete {n} product(s)?",
    bulk_delete_body: "This action cannot be undone. Products used in orders cannot be deleted.",
    bulk_delete_done: "{n} product(s) deleted.",
    bulk_delete_blocked: "{n} product(s) could not be deleted (used in orders).",
    hero_editor: "Home — Hero",
    hero_editor_hint: "The storefront's top banner",
    hero_editor_note: "Leave empty to use the storefront's built-in content. Saving overrides the homepage banner's text and images for all three languages.",
    hero_headline: "Headline & tagline",
    hero_two_lines: "first line",
    hero_title_lead: "Title — line 1",
    hero_title_tail: "Title — line 2",
    hero_support: "Supporting sentence",
    hero_ctas: "Call-to-action buttons",
    hero_primary_cta: "Primary button",
    hero_primary_href: "Primary button link",
    hero_secondary_cta: "Secondary link",
    hero_secondary_href: "Secondary link (URL)",
    hero_images: "Images",
    hero_image_desktop: "Desktop image (landscape)",
    hero_image_mobile: "Mobile image (portrait)",
    hero_image_alt: "Alt text",
    hero_saved: "Banner saved.",
    hero_preview: "Preview",
    hero_preview_hint: "Indicative preview — the published page remains the final reference.",
    hero_preview_no_image: "No image — default banner",
    cost_price: "Cost price",
    margin: "Margin",
    sku: "SKU",
    barcode: "Barcode",
    printer: "Printer",
    kitchen: "Kitchen",
    bar: "Bar",
    oven: "Oven",
    none: "None",
    simple: "Simple",
    variable: "Variable",
    composite: "Composite",
    parent_category: "Parent category",
    top_level: "Top level",
    products_count: "products",
    business: "Business",
    owner: "Owner",
    stores: "Businesses",
    add_store: "New business",
    command_palette_hint: "Search, navigate, act…",
    go_to: "Go to",
    today: "Today",
    last_7_days: "Last 7 days",
    last_30_days: "Last 30 days",
    daily_revenue: "Daily revenue",
    payment_methods: "Payment methods",
    breakdown: "Daily breakdown",
    mark: "Mark",
    tracking_number: "Tracking number",
    mark_shipped: "Mark shipped",
    mark_delivered: "Mark delivered",
    onboarding_title: "Set up your business",
    onboarding_subtitle: "A few details to get started.",
    store_name: "Business name",
    finish: "Finish",
    skip: "Skip",
    welcome: "Welcome",
  },
};

interface LanguageContextValue {
  lang: LangCode;
  isRtl: boolean;
  setLang: (code: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: "fr",
  isRtl: false,
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("fr");

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY) as LangCode | null;
    if (saved === "fr" || saved === "ar" || saved === "en") {
      setLangState(saved);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    window.localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const setLang = useCallback((code: LangCode) => setLangState(code), []);

  const t = useCallback(
    (key: string) => STRINGS[lang][key] ?? STRINGS.fr[key] ?? key,
    [lang],
  );

  const value = useMemo(
    () => ({
      lang,
      isRtl: lang === "ar",
      setLang,
      t,
    }),
    [lang, setLang, t],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
